### ISSUE TITLE
Using ioc start creates iocage/log dataset and iocage_legacy can't handle this

### ISSUE THREAD

**Issue by urosgruber** [iocage/libiocage#68] opened 2017-09-04 20:32 UTC
Creating jail with iocage_legacy `iocage create tag=myjail` and then starting this jail with `ioc start UUID` creates dataset **zpool/iocage/log**

If using `iocage list` after dataset created makes iocage legacy outputing a lot of errors

```
cannot open 'sys/iocage/jails/': invalid dataset name
cannot open 'sys/iocage/jails/': invalid dataset name
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
Error occured: cannot open file /iocage/jails//config: No such file or directory
cannot open 'sys/iocage/jails/': invalid dataset name
cannot open 'sys/iocage/jails/': invalid dataset name
cannot open 'sys/iocage/jails/': invalid dataset name
cannot open 'sys/iocage/jails/': invalid dataset name
  ERROR: missing property or UUID/TAG!
```
Although it outputs list of jails after this errors as usual. 

Destroying **sys/iocage/jails**  manually fixes errors above but after running `ioc start` again recreates dataset.

**Comment by urosgruber** [comment] 2017-09-22 19:28
Any news on this one. Can you actually replicate it or it's some local issue on my machine?

**Comment by igalic** [comment] 2017-09-27 07:42
I'm quite certain that a definite goal is to remain backwards compatible with iocage, and iocage_legacy, but i'm not sure how we could remain forward compatible.??

**Comment by urosgruber** [comment] 2017-09-27 13:21
@igalic but is there a reason that sys/iocage/log dataset is created. Always empty and unused. And I can't find any reference to this.

**Comment by igalic** [comment] 2017-09-27 20:59
@gronke, would you mind weighing in?

**Comment by gronke** [comment] 2017-09-27 21:40
@urosgruber this dataset should not be created. We should address file logging, but this is a fragment from rebuilding the previous version's behavior. Will remove it and open a ticket for event logging.

**Comment by gronke** [comment] 2017-11-15 03:19
@urosgruber I've checked iocage_legacy (1.7.6 and master) list output of after using libiocage https://github.com/iocage/libiocage/commit/e128741b0125b056eae05c03a9ab460179caffea (from master). The log dataset will still be created but should not cause any trouble with iocage_legacy.

**Comment by gronke** [comment] 2017-11-18 22:25
Was able to reproduce this issue with the latest libiocage. Will be fixed in https://github.com/iocage/libiocage/pull/204

**Comment by gronke** [comment] 2017-11-18 22:39
https://github.com/iocage/iocage_legacy/blob/7c712bda3ca1cfd9b5d93dbe57efa75fc1c54c1b/lib/ioc-common#L39-L41 seems to be causing the issue. I'm thinking of moving the logs into the jail datasets.

**Closed** 2017-11-20 18:39 UTC
Labels: bug

**Comment by urosgruber** [comment] 2017-11-20 21:33
All good now except .default dataset is now causing same issue. The thing is any dataset found inside tank/iocage that iocage_legacy does not recognise causes it to misbehave. 

I'm also not sure what is the plan about transition. Is it like using both iocage_legacy and ioc untill all jails migrated or just start using ioc (when released) and migrate jails. If the last is the case then I guess I don't care about this issue and I'll patch iocage_legacy to handle this kind of datasets.

**Comment by gronke** [comment] 2017-11-20 22:11
@urosgruber a migration command is planned. Anyhow the focus is to be compatible with all existing iocage versions first and then aim to migrate across the formats. You can already mix them if you like (e.g. jails newly created with ioc have JSON config format). Jails that are in JSON format are not seen by the iocage version you are using right now.

I need to investigate why the .defaults dataset is causing trouble. It *should* never be created from ioc in case it was not existing before. In this case the preferred defaults storage is JSON. (The order of preference is JSON, UCL, ZFS).
