### ISSUE TITLE
if a jail has no config, ioc throws a stacktrace

### ISSUE THREAD

**Issue by igalic** [iocage/libiocage#65] opened 2017-09-03 16:16 UTC
ioc version is head

```
~ # ioc list -o jid -o name -o release                              
Traceback (most recent call last):                                  
  File "/usr/local/bin/ioc", line 12, in <module>                   
    sys.exit(cli())               
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__                                                     
    return self.main(*args, **kwargs)                               
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main                                                         
    rv = self.invoke(ctx)         
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke                                                      
    return _process_result(sub_ctx.command.invoke(sub_ctx))         
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke                                                       
    return ctx.invoke(self.callback, **ctx.params)                  
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke                                                       
    return callback(*args, **kwargs)                                
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func                                                
    return f(get_current_context(), *args, **kwargs)                
  File "/root/libiocage/libiocage/cli/list.py", line 104, in cli    
    _print_table(jails, columns, header, _sort)                     
  File "/root/libiocage/libiocage/cli/list.py", line 126, in _print_table                                                                
    table_data.append(_lookup_jail_values(jail, columns))           
  File "/root/libiocage/libiocage/cli/list.py", line 176, in _lookup_jail_values                                                         
    columns                       
  File "/root/libiocage/libiocage/cli/list.py", line 175, in <lambda>                                                                    
    lambda column: jail.getstring(column),                          
  File "/root/libiocage/libiocage/lib/Jail.py", line 926, in getstring                                                                   
    return libiocage.lib.helpers.to_string(self.__getattr__(key))   
  File "/root/libiocage/libiocage/lib/Jail.py", line 893, in __getattr__                                                                 
    return object.__getattribute__(self, key)                       
  File "/root/libiocage/libiocage/lib/Jail.py", line 849, in release                                                                     
    name=self.config["release"],  
  File "/root/libiocage/libiocage/lib/JailConfig.py", line 567, in __getitem__                                                           
    return self.defaults[key]     
KeyError: 'release'               
```

this error is specific to the `release` column, since that has no defined default.

**Comment by gronke** [comment] 2017-09-04 00:01
This error was caused by the lack of any configuration format. Neither `config.json` or `config` files nor `org.freebsd.iocage:` zfs properties existed, so that the whole jail user configuration was empty. 

By setting `None` as the default release this was fixed in https://github.com/iocage/libiocage/commit/03c00b0ba3dbf28ae5b8e062bf3ee57000206ade

**Closed by gronke** 2017-09-04 00:01 UTC
Labels: bug
