### ISSUE TITLE
Makefile using invalid pip executable

### ISSUE THREAD

**Issue by urosgruber** [iocage/libiocage#67] opened 2017-09-04 20:22 UTC
Doing a fresh `make` gives 

```
python3.6 -m ensurepip
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: pip in /usr/local/lib/python3.6/site-packages
pkg install -q -y libgit2 libucl cython3
The most recent version of packages are already installed
pip3.6 install -U .
make: exec(pip3.6) failed (No such file or directory)
*** Error code 1

Stop.
```
Renaming `pip3.6` to `pip-3.6` fixes make process. I'm not sure if something is installed on a system differently but I installed pip through pkg.

**Comment by gronke** [comment] 2017-09-10 21:47
> Renaming pip3.6 to pip-3.6 fixes make process. I'm not sure if something is installed on a system differently but I installed pip through pkg.

I've tried installing pip from pkg and via `python3.6 -m ensurepip`  - found the executable at `/usr/local/bin/pip3.6` in both cases. Please re-open if this issue persists.

**Comment by urosgruber** [comment] 2017-09-11 18:52
@gronke hm weird
running `pkg list py36-pip |grep bin` gives me  **/usr/local/bin/pip-3.6**. I'm on 11.1-RELEASE-p1, but I used `pkg install py36-pip`. I'm not sure if that is the case.

**Comment by gronke** [comment] 2017-09-11 19:15
Wait a second.. Something is wrong with this bunch of pips

```
# ls -al /usr/local/bin/ | grep pip
-rwxr-xr-x    1 root  wheel      370 Aug 12 04:55 pip-3.6
-rwxr-xr-x    1 root  wheel      214 Aug 28 12:53 pip3
-rwxr-xr-x    1 root  wheel      214 Aug 28 12:53 pip3.6
```

**Comment by urosgruber** [comment] 2017-09-11 19:28
```
-rwxr-xr-x    1 root  wheel       370 Sep  2 19:01 pip-3.6
-rwxr-xr-x    1 root  wheel       210 Jul 29  2015 pip2
-rwxr-xr-x    1 root  wheel       210 Jul 29  2015 pip2.7
```

**Comment by gronke** [comment] 2017-09-17 14:10
We updated the Makefile and install more dependencies from OS packages. Could not reproduce this issue with the changes applied on FreeBSD 11.1 or HardenedBSD 11.

**Comment by gronke** [comment] 2017-10-02 17:20
I've been able to reproduce. The pip executable is missing when having installed `pkg install py36-pip`. The workaround is to execute `python3.6 -m pip` instead of the pip executable.

**Comment by igalic** [comment] 2017-11-05 11:04
this still not changed in the makefile.?

**Comment by gronke** [comment] 2017-11-15 03:31
fixed in https://github.com/iocage/libiocage/commit/8e4a7673df0f42a42013b6b483ae8921e0639178

**Closed by gronke** 2017-11-15 03:31 UTC
Labels: wontfix
